version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: lego
      MYSQL_DATABASE: keeppley_shop
      MYSQL_USER: keeppley
      MYSQL_PASSWORD: lego
    ports:
      - "3307:3306"
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306 # Đây là cổng của MySQL trong container `database-mysql`
      DB_USER: keeppley
      DB_PASSWORD: lego
      DB_NAME: keeppley_shop
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data: