version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: lego
      MYSQL_DATABASE: keeppley_shop
      MYSQL_USER: keeppley
      MYSQL_PASSWORD: lego
    ports:
      - "3306:3306"
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3002}:${PORT:-3002}"  # Mặc định cổng là 3002 nếu PORT không được đặt
    env_file:
      - .env  # Nạp biến môi trường từ file .env nếu có
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: keeppley
      DB_PASSWORD: lego
      DB_NAME: keeppley_shop
    depends_on:
      - mysql
    networks:
      - my-network
    command: sh -c "sleep 10 && npm start" 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql  # Tên dịch vụ MySQL để phpMyAdmin có thể kết nối
      PMA_USER: keeppley
      PMA_PASSWORD: lego
    ports:
      - "8080:80"  # phpMyAdmin sẽ được truy cập tại http://localhost:8080
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
